[package]
name = "signal_processing"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A signal processing library."
repository = "https://github.com/sigurd4/signal_processing"
keywords = ["signal processing", "dsp", "discrete-time signal processing", "dtsp"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
moddef = "0.2.2"
array_math = {version = "0.2.42", features = ["ndarray"]}
num = "0.4.1"
option_trait = "0.1.16"
rand = "0.8.5"
ndarray = "0.15.6"
ndarray-linalg = {version = "0.16.0", features = ["intel-mkl"]}
statrs = "0.16.0"

[dev-dependencies]
plotters = "0.3.5"
linspace = "0.1.1"
image = "0.25.1"